### ISSUE TITLE
PNG watermark issue?

### ISSUE THREAD

**Issue by alicam** [faressoft/terminalizer#20] opened 2018-08-22 07:16 UTC
I tried adding a watermark PNG. Got this:

```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: Stream not writable
    at module.exports.ChunkStream.write (/usr/local/lib/node_modules/terminalizer/node_modules/pngjs/lib/chunkstream.js:46:24)
    at exports.PNG.PNG.write (/usr/local/lib/node_modules/terminalizer/node_modules/pngjs/lib/png.js:93:16)
    at ReadStream.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at ReadStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at ReadStream.Readable.push (_stream_readable.js:208:10)
    at fs.read (fs.js:2051:12)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:658:17)
```

I'm fairly sure I didn't screw up the path to the file, or any other obvious thing...

I'm on a Mac with Node v8.11.1.

**Comment by faressoft** [comment] 2018-08-22 10:12
Can you please send me the recording file and the watermark ?
Have you tried to edit the same recording file and remove the watermark and then start rendering ?

It seems not related to the watermark itself, Terminalizer renders the frames into png files then merges them into a single gif image.

**Comment by alicam** [comment] 2018-08-22 10:59
Yes I tried to delete the config file completely (to force all defaults) and it still won't render. So yes, it's not about the watermark.

https://gist.github.com/alicam/4a522bdbea889d1061ead09510cc0bbf

That's my demo.yml file, there.

**Comment by alicam** [comment] 2018-08-22 11:01
I'll delete that gist once you've had a look, by the way. I'm not happy to leave it there for long!

**Comment by faressoft** [comment] 2018-08-22 11:33
@alicam I am not able to reproduce the issue on my machine. It is most likely a bug about how the streams are handled in pngjs package, I found an issue about that in their repo. 

So what I am going to do is to release a new release that doesn't pipe a stream into pngjs.

Is this issue happen every time you try to render ? I hope yes so you can help me trying the new approach.

**Comment by faressoft** [comment] 2018-08-23 03:42
@alicam Ops I forgot to do `npm publish` :) Please upgrade and try again :)

**Comment by faressoft** [comment] 2018-08-24 23:26
@alicam Please confirm and close the issue if fixed :)

**Closed** 2018-10-01 16:34 UTC
Labels: bug
