### ISSUE TITLE
Cannot install the package

### ISSUE THREAD

**Issue by hlorofos** [faressoft/terminalizer#56] opened 2019-05-29 05:41 UTC
```
npm install terminalizer --unsafe-perm=true --allow-root

> node-pty-prebuilt@0.7.6 install /root/.npm/node_modules/node-pty-prebuilt
> prebuild-install || node scripts/install.js

prebuild-install WARN install No prebuilt binaries found (target=11.14.0 runtime=node arch=x64 libc= platform=linux)
gyp ERR! configure error
gyp ERR! stack Error: Command failed: /usr/bin/python3 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:299:12)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:999:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:266:5)
gyp ERR! System Linux 3.10.0-862.14.4.el7.x86_64
```

**Comment by erulabs** [comment] 2019-05-30 00:50
I would venture a guess that python3 will not work any time soon. Try swapping to python2?

**Comment by Skarlso** [comment] 2019-06-03 11:36
How about not depending on something that will be obsolete and just making it work with Python3? :)

**Comment by faressoft** [comment] 2019-06-03 11:40
I recommend to switch to a supported version of Node.js and everything will be ok. Please check the supported versions in the README

**Comment by richstokes** [comment] 2019-06-09 20:09
Same issue here on macOS with nom via homebrew

```
v12.4.0
```

**Comment by ohld** [comment] 2019-08-02 20:07
Same with v12.6.0

**Comment by harbi** [comment] 2019-08-04 00:35
Same with terminalizer@0.6.1 on macOS.

**Comment by ohld** [comment] 2019-08-04 09:56
Decided to record the fullscreened terminal with simple Quicktime, sorry.

**Comment by faressoft** [comment] 2019-11-22 20:14
Please try to reinstall it. The new version supports more prebuilds for the node-pty dependency

**Comment by faressoft** [comment] 2019-11-22 20:16
Could you please try to install it again. The issue should be fixed with the new release of Terminalizer.

I am going to close the issue. Feel free to reopen it if you think the issue is not fixed yet.

**Closed by faressoft** 2019-11-22 20:16 UTC
